# Generated by Django 5.1.7 on 2025-03-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.IntegerField(primary_key=True, serialize=False)),
                ('major_name', models.CharField(max_length=100)),
                ('college_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Major',
                'verbose_name_plural': 'Majors',
                'db_table': 'common',
            },
        ),
    ]
